export const languageConfig = {
    c: {
        image: "coderover-cpp-runner",
        fileName: "main.c",
        extension: "c",
        compileCommand: "gcc main.c -O2 -o main",
        executeCommand: "timeout 3s /workspace/main",
        command: "gcc main.c -O2 -o main && timeout 3s ./main < input.txt",
        memory: "256m",
    },
    cpp: {
        image: "coderover-cpp-runner",
        fileName: "main.cpp",
        extension: "cpp",
        compileCommand: "g++ main.cpp -std=c++17 -O2 -o main",
        executeCommand: "timeout 3s /workspace/main",
        command: "g++ main.cpp -std=c++17 -O2 -o main && timeout 3s ./main < input.txt",
        memory: "256m",
    },
    java: {
        image: "coderover-java-runner",
        fileName: "Main.java",
        extension: "java",
        compileCommand: "javac Main.java",
        executeCommand: "timeout 3s java -cp /workspace Main",
        command: "javac Main.java && timeout 3s java Main < input.txt",
        memory: "512m",
    },
    python: {
        image: "coderover-python-runner",
        fileName: "main.py",
        extension: "py",
        compileCommand: "python3 -m py_compile main.py",
        executeCommand: "timeout 3s python3 /workspace/main.py",
        command: "timeout 3s python3 main.py < input.txt",
        memory: "256m",
    },
};
